### ISSUE TITLE
Problem with androidx.fragment:fragment-ktx:1.3.0-rc01

### ISSUE THREAD

**Issue by uberchilly** [Zhuinden/live-event#2]
Hi, I am using I have suddenly started receiving 2 events from one emitted command which crashes my app because it is used to navigate to the next screen. Have you experienced anything similar. 
I am using event-emitter:1.2.0, fragment-ktx:1.3.0-rc01

**Comment by Zhuinden** [comment]
Hi, theoretically you should be capable of getting 2 events only if you emitted 2 commands.

Are you sure that only 1 event happened?

**Comment by uberchilly** [comment]
Well it was an issue in my code with base class emitting as well, so sorry to bother you.
